#!/usr/bin/python3

from ipaddress import ip_network, ip_address
import sys

def main():
    subnets, = sys.argv[1:]
    with open(subnets) as fd:
        subnets = [ip_network(_.strip()) for _ in fd.readlines()]
    for line in sys.stdin:
        try:
            addr = ip_address(line.rsplit(None, 1)[1])
        except Exception:
            addr = None
        if addr is not None and any(addr in n for n in subnets):
            sys.stdout.write(line)

if __name__ == '__main__':
    main()
